static-web:

  image: nginx
  environment:
  - VIRTUAL_HOST=${FQDN}
  - LETSENCRYPT_HOST=${FQDN}
  - LETSENCRYPT_EMAIL=nlog@ditore.ch
  volumes:
  - /srv/nlogclient.www/src:/usr/share/nginx/html:ro
  expose:
  - 80
  restart: unless-stopped
# uncomment if you don't have another proxy
#  port:
#  - 80:80
